version: "3.4"
services:
  db:
    image: mariadb:latest
    container_name: database
    restart: always
    ports:
      - 3306:3306
    environment:
       MYSQL_DATABASE: InterTolls
       MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./database/Tolls.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - app_network
  api:
    restart: always
    container_name: api
    build:
      dockerfile: Dockerfile
      context: "./api"
    environment:
      - HOST_NAME=db
    depends_on:
      - db
    volumes:
      - ./database:/database
      - ./api:/api
      - ./backend:/backend
    ports:
      - 9103:9103
    networks:
      - app_network
  cli:
    container_name: cli
    build:
      dockerfile: Dockerfile
      context: "./cli"
    depends_on:
      - api
    volumes:
      - ./test-cli:/home/intertolls/test-cli
    environment:
      - API_HOST_NAME=api
      - DB_HOST_NAME=db
    networks:
      - app_network
    tty: true
    stdin_open: true
  web:
    image: php:7.4-apache
    container_name: web-app
    volumes:
      - ./frontend:/var/www/html/
    ports:
      - 8000:80
    environment:
      - HOST_NAME=api
    depends_on:
      - api
    networks:
      - app_network
  
networks:
  app_network:
      driver: bridge